### ISSUE TITLE
Customize the views?

### ISSUE THREAD

**Issue by kershnerd** [mamuz/MamuzBlog#10]
Is there a way to customize the views?

**Comment by mamuz** [comment]
Hi, sure you can.
You can implement your own view templates by overwriting the template map.
Create a new view template file and set it to your config to the specific alias you wish to overwrite.

See [this](https://github.com/mamuz/mm-web/blob/master/config/autoload/blog.global.php) as example.

**Comment by kershnerd** [comment]
I was able to override the 'mamuz-blog/post-query/published-posts' view and get this working correctly and I can see the blog list.  Here is a screen shot to show this:

![goferhost_dev_blog](https://cloud.githubusercontent.com/assets/5776369/5797032/a9f6eed0-9f6f-11e4-8669-9eca4dc1c698.jpg)

Is there a .phtml file I can override for the actual short and long panel view customization?  I see the View Helpers for PostPanelShort.php and PostPanel.php but no where can I find the actual views.

**Comment by kershnerd** [comment]
I have the main blog template overriden and working well.

![goferhost_dev_blog](https://cloud.githubusercontent.com/assets/5776369/5797126/a356a870-9f71-11e4-8a96-356c45ca16e6.jpg)

Now I need to customize the panels.  I see there is a view helper for the Panel.  What is the best way to override that?  I don't think it is correct to just change your Panel.php.  What is the best way to override this?

Thanks so much!

**Comment by kershnerd** [comment]
Since I have the $entity in the published-posts.phtml view, I have all the information I need to create my view.  I will just create the blog view without calling your view helpers and this will work fine.  :)
