### ISSUE TITLE
Feature Request: unique constraint on Tag name

### ISSUE THREAD

**Issue by kershnerd** [mamuz/MamuzBlog#12]
I recommend you add a unique constraint for the table MamuzBlogTag's name porperty.  I can't see a reason that you would want the same tag name in there.

    /**
     * @ORM\Column(type="string", nullable=false, unique = true)
     * @Annotation\Filter({"name":"StripTags"})
     * @Annotation\Filter({"name":"StringTrim"})
     * @Annotation\Validator({"name":"Alnum", "options": {"allowWhiteSpace":"false"}})
     * @Annotation\Validator({"name":"StringLength", "options": {"min":"1", "max":"255"}})
     * @Annotation\Options({"label":"Name"})
     * @Annotation\Required()
     * @var string
     */
    private $name = '';

**Comment by mamuz** [comment]
:+1:  you can make a PR.
