### ISSUE TITLE
How can I get the Post URL in the Posts view?

### ISSUE THREAD

**Issue by kershnerd** [mamuz/MamuzBlog#13]
In my over ride for published-posts.phtml view, there is a collection of $entity.  Entities contain title, description, id, etc...

How can I get a create a link to a particular blog post since I don't have the encrypted article ID in the view?

I tried to get it by title, but this doesn't seem to work:
"/blog/post/<?php echo urlencode($entity->getTitle()); ?>"

**Comment by mamuz** [comment]
You can use the [PermaLinkPost](https://github.com/mamuz/MamuzBlog/blob/master/src/MamuzBlog/View/Helper/PermaLinkPost.php) view helper for this.

Inside view template..
```php
$this->postPanelShort($entity)
```

Inside view helper..
```php
$this->getView()->permaLinkPost($this->entity);
```

**Comment by kershnerd** [comment]
That is exactly what I needed... Thanks!
