### ISSUE TITLE
Question about blog URL

### ISSUE THREAD

**Issue by kershnerd** [mamuz/MamuzBlog#14]
I have this all working and your software is almost perfect for what I was needing, so thanks...

My question is that I can get the URL correctly with the encrypted permalink, but is there a more user friendly way to access a blog article?

For example, instead of this: 
/blog/post/VqmX3Xkv9/domain-name-privacy

but like this:
/blog/post/domain-name-privacy
 or even
/blog/domain-name-privacy

**Comment by mamuz** [comment]
In current state of that module there isn't a more user friendly way.
You can use another controller, where you map blog title to a specific id.
But you have to consider a blog title is changeable and not unique, which ends up in appending increment values and sourcing title changes.

**Comment by kershnerd** [comment]
First of all, I love this code more than you know!  Excellent job!

I think that for SEO reasons, it makes sense to make the blog article url as user friendly as possible.  I realize your concern about titles changing and possibly not being unique and that makes sense.

In my opinion (at least for my project), I think it would make sense to have the URL in the form of:
website.com/blog/this-is-this-title

Do you think this can be accomplished with a URL rewrite rule (1 for each article)?  Or do you think a new controller should be created to fetch by title (assuming titles are unique)?

**Comment by mamuz** [comment]
Hi,

For `website.com/blog/this-is-this-title` you don't need url rewriting. Title is fetchable by route parameters. So you have to change controller logic. Problem is dedicated blog post retrieval by title is not supported.

One suggestion is to add a listener to controller dispatch event. Inside this you can add logic to map the title to an encrypted id directly by query database.
